[project]
name = "gm-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "grpcio>=1.71.0",
    "grpcio-tools>=1.71.0",
]
